# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Automata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('final', models.BooleanField(default=False)),
                ('initial', models.BooleanField(default=False)),
                ('automata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.Automata')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.Automata')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='convert.States')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.Alphabet')),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='convert.States')),
            ],
        ),
        migrations.AddField(
            model_name='alphabet',
            name='automata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.Automata'),
        ),
    ]
